name: Python ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data ingestion
        run: |
          python -c "from src.components.data_ingestion import DataIngestion; obj = DataIngestion(); obj.initiate_data_ingestion()"

      - name: Run data transformation
        run: |
          python -c "from src.components.data_transformation import DataTransformation; dt = DataTransformation(); train_arr, test_arr, _ = dt.initiate_data_transformation('artifacts/train.csv', 'artifacts/test.csv')"

      - name: Train model
        run: |
          python -c "from src.components.model_trainer import ModelTrainer; mt = ModelTrainer(); import pandas as pd; train_arr = pd.read_csv('artifacts/train.csv').to_numpy(); test_arr = pd.read_csv('artifacts/test.csv').to_numpy(); print(mt.initiate_model_trainer(train_arr, test_arr))"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: artifacts/
